---
title: "R Notebook"
output: html_notebook
---

```{r}
theme_set(theme_bw()+
            theme(strip.background =element_rect(fill="white", color = "darkgrey"),
                  panel.background = element_rect(fill = "#F2F2F2"),
                  panel.grid = element_line(colour = "#D8D8D8"),
                  panel.border = element_rect(color = "darkgrey"),
                  axis.title.x = element_text(margin = margin(t = 10)),
                  axis.title.y = element_text(margin = margin(r = 10))))
```


```{r message=FALSE, warning=FALSE, include=FALSE}
setwd("C:/Users/sandrine/Documents/R_script/Planaqua_experiment")
source("R/model_final/MODEL_visualisation_function.R")
source("R/setup.R")
```


```{r}

load("Model_Treatment.RData")
load("Model_Treatment_time_and_lake.RData")
load("Model_Treatment_time_x_lake.RData")
load("Model_Treatment_capture.RData")
load("Model_Treatment_capture_p1.RData")
  
  
list_model = list(
  Model_Treatment,
  Model_Treatment_time_and_lake,
  Model_Treatment_time_x_lake,
  Model_Treatment_capture,
  Model_Treatment_capture_p1
)

model_name = c(
  "Model_Treatment",
  "Model_Treatment_time_and_lake",
  "Model_Treatment_time_x_lake",
  "Model_Treatment_capture",
  "Model_Treatment_capture_p1"
)
```

```{r}
plot_deviance(list_model,model_name)
```


```{r}
for (i in 1:5){
  model = list_model[[i]]
  print(plot_p(model)+
    labs(title= model_name[i]))
}
```

```{r fig.height=6, fig.width=10, message=FALSE}
for (i in 1:5){
  model = list_model[[i]]
  print(plot_phi(model)+
    labs(title= model_name[i]))
}
```

```{r fig.height=6, fig.width=10}
for (i in 1:5){
  model = list_model[[i]]
  print(plot_psi(model)+
    labs(title= model_name[i]))
}
```


```{r fig.height=6, fig.width=10}
for (i in 4:5){
  model = list_model[[i]]
  print(plot_epsilon(model)+
    labs(title= model_name[i]))
}
```


```{r}
quantile(as.mcmc(Model_Treatment_capture)[[2]][,"error"], probs = 0.025, digits = )
mean(as.mcmc(Model_Treatment_capture)[[2]][,"error"])
print(Model_Treatment_capture$summary)
```

```{r}
quantile(as.mcmc(Model_Treatment_capture_p1)[[2]][,"p3"], probs = 0.025, digits = )
mean(as.mcmc(Model_Treatment_capture_p1)[[2]][,"p3"])
quantile(as.mcmc(Model_Treatment_capture_p1)[[2]][,"p3"],0.975)
```

Toutes les figures pour mon rapport
```{r fig.height=4, fig.width=8}
model = Model_Treatment_capture

ggplot(get_p(model))+
  geom_point(aes(x = Size, y = mean))+
  geom_errorbar(aes(x = Size, 
                    ymin = min, ymax = max), width = 0.4)+
  labs(y = "Capture probability", x = "Size group")+
  ylim(0,1)

ggplot(get_phi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = Treatment, y = mean))+
  geom_errorbar(aes(x = Treatment, ymin = min, ymax = max), width = 1)+
  scale_color_discrete("Treatment")+
  facet_wrap(~Size)+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Survival probability")+
  ylim(0,1)

ggplot(get_psi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = Treatment, y = mean))+
  geom_errorbar(aes(x = Treatment, ymin = min, ymax = max), width = 1)+
  facet_wrap(~Size)+
  scale_color_discrete("Treatment")+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Growth probability")+
  ylim(0,1)

ggplot(get_n(model))+
  geom_bar(stat = "identity", aes(x = Year, y = mean, fill = Size))+
  #geom_errorbar(aes(x = Year, ymin =min, ymax = max))+
  scale_fill_manual (values =c("#FED98E","#FE9929","#CC4C02"))+
  labs(y = "Abundance")+
  facet_wrap(~Treatment)

ggplot(get_epsilon(model))+
  geom_point(aes(x = factor(Lake), y = mean))+
  geom_errorbar(aes(x = factor(Lake), ymin = min, ymax = max), width = 0.4)+
  facet_wrap(~Year)+
  labs(x = "Lake", y = "Epsilon distribution probability")

```

```{r fig.height=4, fig.width=7}
p1 <- ggplot(get_phi(model) %>% filter(Exp_time == "Before treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = Treatment, y = mean), show.legend = F)+
  geom_errorbar(aes(x = Treatment, ymin = min, ymax = max), width = 1, show.legend = F)+
  scale_color_discrete("Treatment")+
  facet_wrap(~Size)+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Survival probability")+
  ylim(0,1)

p2 <- ggplot(get_psi(model) %>% filter(Exp_time == "Before treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = Treatment, y = mean))+
  geom_errorbar(aes(x = Treatment, ymin = min, ymax = max), width = 1)+
  facet_wrap(~Size)+
  scale_color_discrete("Treatment")+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Growth probability")+
  ylim(0,1)

p1+
  labs(title="A")+
p2+
  labs(title = "B")
```

```{r fig.height=4, fig.width=8}
model = Model_Treatment_capture_p1

p1 <- ggplot(get_p(model))+
  geom_point(aes(x = Size, y = mean))+
  geom_errorbar(aes(x = Size, 
                    ymin = min, ymax = max), width = 0.4)+
  labs(y = "Capture probability", x = "Size group")+
  ylim(0,1)

p2 <- ggplot(get_phi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = Treatment, y = mean), show.legend = F)+
  geom_errorbar(aes(x = Treatment, ymin = min, ymax = max), width = 1, show.legend = F)+
  scale_color_discrete("Treatment")+
  facet_wrap(~Size)+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Survival probability")+
  ylim(0,1)

p3 <- ggplot(get_psi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = Treatment, y = mean))+
  geom_errorbar(aes(x = Treatment, ymin = min, ymax = max), width = 1)+
  facet_wrap(~Size)+
  scale_color_discrete("Treatment")+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Growth probability")+
  ylim(0,1)

ggplot(get_n(model))+
  geom_bar(stat = "identity", aes(x = Year, y = mean, fill = Size))+
  #geom_errorbar(aes(x = Year, ymin =min, ymax = max))+
  scale_fill_manual (values =c("#FED98E","#FE9929","#CC4C02"))+
  labs(y = "Abundance")+
  facet_wrap(~Treatment)

p4 <- ggplot(get_epsilon(model))+
  geom_point(aes(x = factor(Lake), y = mean))+
  geom_errorbar(aes(x = factor(Lake), ymin = min, ymax = max), width = 0.4)+
  facet_wrap(~Year)+
  labs(x = "Lake", y = "Epsilon distribution probability")
```

```{r}
(p1+p4) / (p2+p3)
```

```{r fig.height=2, fig.width=4}
p4
```


```{r}
t_2021 <- BDD_g %>% filter(Year == 2021 & Tag_id %in% s$Tag_id & !is.na(s_group)) %>% group_by(Lake,Treatment,s_group) %>% summarize(n_2021 = n())
t_new <- BDD_g %>% mutate (catch_2021 = case_when(Year == "2021" ~ TRUE,
                                      Tag_id %in% subset(BDD_g , !is.na(Tag_id) & Year == "2021")$Tag_id ~ TRUE,
                                      TRUE ~ FALSE)) %>%
  filter(Year == 2022& Tag_id %in% s$Tag_id & !is.na(s_group) & !catch_2021) %>% group_by(Lake,Treatment,s_group) %>% summarize(n_new = n())
t_recatch <- BDD_g %>% mutate (catch_2021 = case_when(Year == "2021" ~ TRUE,
                                      Tag_id %in% subset(BDD_g , !is.na(Tag_id) & Year == "2021")$Tag_id ~ TRUE,
                                      TRUE ~ FALSE)) %>%
  filter(Year == 2022& Tag_id %in% s$Tag_id & !is.na(s_group) & catch_2021) %>% group_by(Lake,Treatment,s_group) %>% summarize(n_catch = n())
  
t <-merge(t_2021,t_new, all = T)
t <- merge(t,t_recatch, all = T)
t[is.na(t)]<- 0

t <- t %>% mutate(mean = n_2021 +n_new*(n_2021/n_catch))
t[is.na(t)]<- 0
t <- t %>% ungroup() %>% group_by(Treatment, s_group) %>% summarize (mean =sum(mean))
t <- t %>% mutate(Year = "Obs", min = NA, max = NA) %>% mutate(Treatment = factor(Treatment, levels = c(1,2,3,4), labels = Treatment_name),
s_group = factor(s_group, levels = c(1,2,3), labels = c("Small","Medium","Large")))
colnames(t) <- c("Treatment", "Size","mean","Year","min","max")

aux <- BDD_g %>% filter(Year == 2022 & Tag_id %in% s$Tag_id & !is.na(s_group) & s_group != 0) %>% group_by(Treatment, s_group) %>% summarize (mean = n()) %>% mutate(Year = "2022", min = NA, max = NA) %>% mutate(Treatment = factor(Treatment, levels = c(1,2,3,4), labels = Treatment_name),
                                                                                                                                                                                             s_group = factor(s_group, levels = c(1,2,3), labels = c("Small","Medium","Large")))
colnames(aux) <- c("Treatment", "Size","mean","Year","min","max")

n2 <- rbind(n,t)
```

```{r fig.height=6, fig.width=11}
#n <- get_n(model)
ggplot(n,aes(y = mean, x = Year, color = Treatment))+
  geom_point(aes(y = mean, x = Year, color = Treatment))+
  #geom_line(aes(group = Treatment))+
  geom_errorbar(aes(ymin = min, ymax = max, x = Year, color = Treatment))+
  facet_grid(rows = vars(Size), cols = vars(Treatment))+
  labs(y = "Abundance")

ggplot(n2,aes(y = mean, x = Year, color = Treatment))+
  geom_point(aes(y = mean, x = Year, color = Treatment))+
  #geom_line(aes(group = Treatment))+
  geom_errorbar(aes(ymin = min, ymax = max, x = Year, color = Treatment))+
  facet_grid(rows = vars(Size), cols = vars(Treatment))+
  labs(y = "Abundance")
```

```{r}

```


