---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readxl)
BDD <- read_excel("./data/data_final.xlsx", col_types = c("numeric","date","text","text","text","text","text","text","text","numeric","numeric","text","text"), na = "")
BDD <- BDD %>% mutate (Year = as.factor(format(Date,"%Y")))
BDD <- BDD %>% filter(Species == "roach" & !is.na(Weight) & Method_capture != "creel" & ! Tag_id %in% c("juvenile","no_tag"))
```

```{r}
BDD <- subset(BDD, Year %in% c(2022,2021) & Tag_id %in% subset(BDD, Year == "2021")$Tag_id & Tag_id %in% subset(BDD, Year == "2022")$Tag_id)
```

```{r}
a <- ggplot(BDD)+
  geom_point(aes(x = Year, y = Weight))+
  geom_line(aes(x = Year, y = Weight, group = Tag_id))+
  labs(title = "A")
b <- ggplot(BDD)+
  geom_density(aes(x = Weight, color = Year))+
  labs(title = "B")

c <- ggplot(BDD)+
  geom_point(aes(x = Year, y = Size))+
  geom_line(aes(x = Year, y = Size, group = Tag_id))+
  labs(title = "C")
d <- ggplot(BDD)+
  geom_density(aes(x = Size, color = Year))+
  labs(title = "D")


  (a+b)/(c+d)
```

```{r}
ggplot(BDD_g)+
  geom_density(aes(x = Size, color = Year))+
  geom_segment(aes(x = 120, xend = 120, y = 0, yend = 0.04), size = 1, linetype = "dotted")+
  geom_segment(aes(x = 180, xend = 180, y = 0, yend = 0.04))+
  facet_wrap(~factor(Treatment, levels = c(1,2,3,4),labels = Treatment_name))+
  labs(y = "Density")
```

