---
title: "Model result visualisation"
output: github_document
---

```{r echo = FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE, warning=FALSE)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
#source("./setup.R")
#source("./MODEL_visualisation_function.R")

load("Model_Treatment.RData")
load("Model_Treatment_2022.RData")
load("Model_Treatment_capture.RData")
load("Model_Treatment_capture_reverse.RData")
```

```{r}
theme_set(theme_bw()+
            theme(strip.background =element_rect(fill="white", color = "darkgrey"),
                  panel.background = element_rect(fill = "#F2F2F2"),
                  panel.grid = element_line(colour = "#D8D8D8"),
                  panel.border = element_rect(color = "darkgrey"),
                  axis.title.x = element_text(margin = margin(t = 10)),
                  axis.title.y = element_text(margin = margin(r = 10))))
```

## Capture Probability and variability
### Mean capture probability
```{r fig.height=4, fig.width=8}
model = Model_Treatment_2022

ggplot(get_p(model))+
  geom_point(aes(x = Size, y = mean))+
  geom_errorbar(aes(x = Size, 
                    ymin = min, ymax = max), width = 0.4)+
  labs(y = "Capture probability", x = "Size group")+
  ylim(0,1)
```

### Variation around mean capture probability for each event
```{r fig.height=4, fig.width=8}
ggplot(get_epsilon(model))+
  geom_point(aes(x = factor(Lake), y = mean))+
  geom_errorbar(aes(x = factor(Lake), ymin = min, ymax = max), width = 0.4)+
  facet_wrap(~Year)+
  labs(x = "Lake", y = "Epsilon distribution probability")
```

## Survival

```{r fig.height=4, fig.width=8}
# color for nutrients (in my oral pres) : ,type = c("#31B404","#6E6E6E","#31B404","#6E6E6E")

ggplot(get_phi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = factor(Treatment), y = mean))+
  geom_errorbar(aes(x = factor(Treatment), ymin = min, ymax = max), width = 1)+
  scale_color_discrete("Treatment")+
  facet_wrap(~Size)+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Survival probability")+
  ylim(0,1)
```

## Growth

```{r fig.height=4, fig.width=8}
ggplot(get_psi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = factor(Treatment), y = mean))+
  geom_errorbar(aes(x = factor(Treatment), ymin = min, ymax = max), width = 1)+
  facet_wrap(~Size)+
  scale_color_discrete("Treatment")+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Growth probability")+
  ylim(0,1)
```

## Abundance

```{r fig.height=4, fig.width=8}
ggplot(get_n(model),aes(y = mean, x = Year, color = Treatment))+
  geom_point(aes(y = mean, x = Year, color = Treatment))+
  #geom_line(aes(group = Treatment))+
  geom_errorbar(aes(ymin = min, ymax = max, x = Year, color = Treatment))+
  facet_grid(rows = vars(Size), cols = vars(Treatment))+
  labs(y = "Abundance")+
  geom_point(data = bn, aes(x="2022",y=n))
```

```{r}
bn <- BDD_p %>% filter(Year=="2022") %>% group_by(Treatment, s_group) %>% summarize(n = n()) %>% filter(s_group !="0" & !is.na(s_group))
colnames(bn) <- c("Treatment","Size","n")
bn <- bn %>% mutate(Treatment = factor(Treatment, level = c(1,2,3,4), labels = c("Perch- / Nutrients+","Perch+ / Nutrients+","Perch- / Nutrients-","Perch+ / Nutrients-")),
                    Size = factor(Size, level = c(1,2,3), labels = c("Small","Medium","Large")))
ggplot(bn)+
  geom_point(aes(x=1,y=n))+
  facet_grid(rows = vars(Size), cols = vars(Treatment))
```

## You can get a table of the result with uncertainty :

```{r, echo = TRUE, result = FALSE}
knitr::kable(head(data.frame(Model_Treatment_capture[[2]][10])))
```

```{r fig.height=5, fig.width=10}
load("Model_Treatment_capture_reverse.RData")
model = Model_Treatment_capture_reverse
p1 <- ggplot(get_phi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = factor(Treatment), y = mean))+
  geom_errorbar(aes(x = factor(Treatment), ymin = min, ymax = max), width = 1)+
  scale_color_discrete("Treatment")+
  facet_wrap(~Size)+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Survival probability")+
  ylim(0,1)

p2 <- ggplot(get_psi(model) %>% filter(Exp_time == "After treatment"), aes(color = factor(Treatment)))+
  geom_point(aes(x = factor(Treatment), y = mean))+
  geom_errorbar(aes(x = factor(Treatment), ymin = min, ymax = max), width = 1)+
  facet_wrap(~Size)+
  scale_color_discrete("Treatment")+
  theme(axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title.x=element_blank())+
  labs(y = "Growth probability")+
  ylim(0,1)

p1+p2
```

```{r}
traceplot(model,ask=F)
```

