---
title: "R Notebook"
output: html_notebook
---
 

```{r}
ggplot(subset(BDD_g, Tag_id %in% subset(BDD_a, Year == "2016" & Size > 120)$Tag_id), aes(x = Year, y  = Size, color = Treatment))+
  geom_line(aes(group = Tag_id))+
  geom_point()#+
  #color_brewer_scale(palette ="Set2")

ggplot(BDD_g, aes(x = Year, y  = Size, color = Treatment))+
  geom_line(data = BDD_a, aes(group = Tag_id))+
  geom_point()+
  geom_point(data = BDD_g %>% filter (Tag_id %in% c("juvenile")), aes(color = "juvenile"))+
  scale_colour_manual(values = c("1" = "indianred1","2" = "deepskyblue2","3" = "chartreuse3","4" = "mediumorchid3","juvenile"="grey"))+
  facet_wrap(~ Treatment)+
  labs ( x = "Size (mm)", y = "Year")
  #labs(title = "Evolution of roachs size by year of capture")

ggplot(BDD_g)+
  geom_bar(aes(x = Year, fill = Tag_year),position = position_stack(reverse = TRUE))+
  scale_fill_brewer(palette = "YlOrBr", direction = -1)

ggplot(BDD_g %>% filter (Year == "2022"))+
  geom_bar(aes(x = Lake, fill = Tag_year),position = position_stack(reverse = TRUE))+
  scale_fill_brewer(palette = "YlOrBr", direction = -1)+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter(Year == "2022"))+
  geom_bar(aes(x = Treatment, fill = Treatment))

ggplot(BDD_g %>% filter (Tag_year == "2016"), aes(x = Year, y  = Size, color = Treatment))+
  geom_line(aes(group = Tag_id))+
  geom_point()

ggplot(BDD_p , aes(x = Year, y  = Size, color = Treatment))+
  #geom_line(aes(group = Tag_id))+
  geom_point()+
  facet_wrap(~ Treatment)

ggplot(BDD_g %>% filter(Tag_year == "2016" & Year == "2016"))+
  geom_density(aes(x = Size))

ggplot(BDD_g)+
  geom_histogram(aes(x = Size, color = Tag_year), binwidth = 2)+
  facet_wrap(~ Lake)


```

```{r}
ggplot(BDD_p)+
  geom_bar(aes(x = Year, fill = Tag_year),position = position_stack(reverse = TRUE))+
  scale_fill_brewer(palette = "YlOrBr", direction = -1)

ggplot(BDD_p %>% filter (Year == "2022"))+
  geom_bar(aes(x = Lake, fill = Tag_year),position = position_stack(reverse = TRUE))+
  scale_fill_brewer(palette = "YlOrBr", direction = -1)+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter (Year == "2021"))+
  geom_bar(aes(x = Lake))+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter (Year == "2020"))+
  geom_bar(aes(x = Lake))+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter (Year == "2019"))+
  geom_bar(aes(x = Lake))+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter (Year == "2018"))+
  geom_bar(aes(x = Lake))+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter (Year == "2017"))+
  geom_bar(aes(x = Lake))+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p %>% filter (Year == "2016"))+
  geom_bar(aes(x = Lake))+
  facet_wrap(~Treatment, scales= "free_x")

ggplot(BDD_p)+
  geom_density(aes(x = Size, color = Year))
```

```{r}
pn1 <- BDD_p %>% filter (Passage_net == 1) %>% group_by(Year,Lake) %>% summarise(nb1 = n()) %>% ungroup()
pn2 <- BDD_p %>% filter (Passage_net == 2) %>% group_by(Year,Lake) %>% summarise(nb2 = n()) %>% ungroup()
pn3 <- BDD_p %>% filter (Passage_net == 3) %>% group_by(Year,Lake) %>% summarise(nb3 = n()) %>% ungroup()

pn <- merge(pn1,pn2, all = TRUE) %>% merge(pn3, all = TRUE)
pn[is.na(pn)] <- 0

pn <- pn %>% mutate(p1 = (nb1-nb2)/nb1, 
                    p2 = (nb2-nb3)/nb2, 
                    p3 = (nb1-nb3)/(nb2+nb1))
pn
```

```{r}
ggplot(BDD_p %>% filter(Tag_year == "2016" & Year == "2022"))+
  geom_density(aes(x = Size, color = Treatment))
```

```{r}
pn1 <- BDD_g %>% filter (Passage_net == 1) %>% group_by(Year,Lake) %>% summarise(nb1 = n()) %>% ungroup()
pn2 <- BDD_g %>% filter (Passage_net == 2) %>% group_by(Year,Lake) %>% summarise(nb2 = n()) %>% ungroup()
pn3 <- BDD_g %>% filter (Passage_net == 3) %>% group_by(Year,Lake) %>% summarise(nb3 = n()) %>% ungroup()

pn <- merge(pn1,pn2, all = TRUE) %>% merge(pn3, all = TRUE)
pn[is.na(pn)] <- 0

pn <- pn %>% mutate(p1 = (nb1-nb2)/nb1, 
                    p2 = (nb2-nb3)/nb2, 
                    p3 = (nb1-nb3)/(nb2+nb1))
pn <- pn %>% mutate(diff = ifelse(p1 == 1, 0,p1-p2))
```


```{r}
colnames(BDD_g)
head(BDD_g %>% select(Date, Lake, Tag_id, Obs_status, Size, Weight, Treatment))
```

```{r}
nrow(BDD_g %>% filter (Tag_year == "2017" & Year == "2017"))
nrow(BDD_g %>% filter (Tag_year == "2016" & Year == "2016"))
```

```{r}
#size_break <- c(0,120,180,300)
#BDD_g <- BDD_g %>% mutate(s_group = discretize(Size ,method = "fixed",
#                            breaks = size_break, 
#                            labels= c(1:(length(size_break)-1))))
ggplot(BDD_g)+
  geom_bar(aes(x = Year, fill = s_group))+#,position = position_stack(reverse = TRUE))+
  #scale_fill_brewer(palette = "YlOrBr")+#, direction = -1)+
  facet_wrap(~Treatment)

#En récupérent que ce que j'étudie

ggplot(BDD_g %>% filter(Tag_id %in% s$Tag_id & !is.na(s_group)))+
  geom_bar(aes(x = Year, fill = s_group))+#,position = position_stack(reverse = TRUE))+
  scale_fill_brewer(palette = "YlOrBr")+#, direction = -1)+
  facet_wrap(~Treatment)

BDD_g %>% filter(Tag_id %in% s$Tag_id & is.na(s_group))
```

```{r}
sum <- BDD_g %>% filter(!is.na(s_group)) %>% group_by(s_group,Year,Treatment,Lake) %>% summarize(n = n())

ggplot(sum)+
  geom_boxplot(aes(y = n, x = Treatment))+
  geom_jitter(aes(y = n, x = Treatment, color = Year))+
  facet_wrap(~ s_group)
```

```{r}
ggplot(BDD_g %>% filter(Year == "2016"))+
  geom_bar(aes(x= Lake, fill =s_group))
```





