---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(R2jags)
```

# Importation de tous les models

```{r}
# Model avec tous les poissons



variable_model <-  c("t0 ~ i",
           "L ~ tr, t0 ~ i",
           "K ~ tr, t0 ~ i",
           "K ~ tr, L ~ tr, t0 ~ i",
           
           "2016 : K ~ la, L ~ la, t0 ~ i",
           
           "2016 : t0 ~ i",
           "2016 : L ~ tr, t0 ~ i",
           "2016 : K ~ tr, t0 ~ i",
           "2016 : K ~ tr, L ~ tr, t0 ~ i",
           
           "2016 : K ~ tr, L ~ tr",
           "2016 : K ~ la, L ~ la",
           "2016 : K ~ tr + (1|la), L ~ tr + (1|la)",
           "2016 : K ~ tr + (1|la), L ~ tr + (1|la), t0 ~ i")

nom_model <- c ("Model_g_t0i", 
                   "Model_g_Ltr_t0i", 
                   "Model_g_Ktr_t0i", 
                    "Model_g_Ktr_Ltr_t0i",
                    
                    "Model_g_Kla_Lla_t0i_2016",
                    
                    "Model_g_t0i_2016",
                    "Model_g_Ltr_t0i_2016",
                    "Model_g_Ktr_t0i_2016", 
                    "Model_g_Ktr_Ltr_t0i_2016",
                    
                    # "Model_g_2016",
                    
                    "Model_g_Ktr_Ltr_2016",
                    # "Model_g_Ktr_2016",
                    # "Model_g_Ltr_2016",
                    
                    # "Model_g_Lla_2016",
                    # "Model_g_Kla_2016",
                    "Model_g_Kla_Lla_2016",
                    
                    "Model_g_Ktrla_Ltrla_2016",
                    "Model_g_Ktrla_Ltrla_t0i_2016")


load ("object/Model_g_t0i.RData")
load("object/Model_g_Ltr_t0i.RData")
load("object/Model_g_Ktr_t0i.RData")
load("object/Model_g_Ktr_Ltr_t0i.RData")

# Model de 2016

load ("object/Model_g_t0i_2016.RData")
load("object/Model_g_Ltr_t0i_2016.RData")
load("object/Model_g_Ktr_t0i_2016.RData")
load("object/Model_g_Ktr_Ltr_t0i_2016.RData")

load("object/Model_g_Ktrla_Ltrla_t0i_2016.RData")
load("object/Model_g_Kla_Lla_t0i_2016.RData")

# Model 2016 sans t0 variable

load("object/Model_g_Ktr_Ltr_2016.RData")
load("object/Model_g_Ktrla_Ltrla_2016.RData")
load("object/Model_g_Kla_Lla_2016.RData")

list_model <- list (Model_g_t0i, 
                    Model_g_Ltr_t0i, 
                    Model_g_Ktr_t0i, 
                    Model_g_Ktr_Ltr_t0i,
                    
                    Model_g_Kla_Lla_t0i_2016,
                    
                    Model_g_t0i_2016,
                    Model_g_Ltr_t0i_2016,
                    Model_g_Ktr_t0i_2016, 
                    Model_g_Ktr_Ltr_t0i_2016,
                    
                    # Model_g_2016
                    
                    Model_g_Ktr_Ltr_2016,
                    # Model_g_Ktr_2016,
                    # Model_g_Ltr_2016,
                    
                    # Model_g_Lla_2016,
                    # Model_g_Kla_2016,
                    Model_g_Kla_Lla_2016,
                    
                    Model_g_Ktrla_Ltrla_2016,
                    Model_g_Ktrla_Ltrla_t0i_2016)

```

# Model tout poissons


```{r}
print(Model_g_t0i, digits = 3)
traceplot(Model_g_t0i, ask =FALSE)
autocorr.plot(Model_g_t0i, ask = FALSE)
```

```{r}
print(Model_g_Ktr_t0i, digits = 3)
traceplot(Model_g_Ktr_t0i, ask =FALSE)
autocorr.plot(Model_g_Ktr_t0i, ask = FALSE)
```

```{r}
print(Model_g_Ltr_t0i, digits = 3)
traceplot(Model_g_Ltr_t0i, ask =FALSE)
autocorr.plot(Model_g_Ltr_t0i)

param <- data.frame(rbind(as.mcmc(Model_g_Ltr_t0i)[[1]],as.mcmc(Model_g_Ltr_t0i)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")
```

```{r}
print(Model_g_Ktr_Ltr_t0i, digits = 3)
traceplot(Model_g_Ktr_Ltr_t0i, ask =FALSE)
autocorr.plot(Model_g_Ktr_Ltr_t0i)

param <- data.frame(rbind(as.mcmc(Model_g_Ktr_Ltr_t0i)[[1]],as.mcmc(Model_g_Ktr_Ltr_t0i)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")

ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.2.), color = "blue")+
  geom_density(aes(x = K.3.), color = "green")+
  geom_density(aes(x = K.4.), color = "black")

ggplot()+
  geom_point(aes(x = 1:8, y = 2.1*144*exp(-2.1*(1:8+1.3))), color = "red")+
  geom_point(aes(x = 1:8, y = 1.5*154*exp(-1.5*(1:8+1.3))), color = "blue")+
  geom_point(aes(x = 1:8, y = 5*136*exp(-5*(1:8+1.3))), color = "green")+
  geom_point(aes(x = 1:8, y = 1.2*156*exp(-1.2*(1:8+1.3))))
```


```{r}
print(Model_g_t0i_2016, digits = 3)
traceplot(Model_g_t0i_2016, ask =FALSE)
autocorr.plot(Model_g_t0i_2016)
```

```{r}
print(Model_g_Ktr_t0i_2016, digits = 3)
traceplot(Model_g_Ktr_t0i_2016, ask =FALSE)
autocorr.plot(Model_g_Ktr_t0i_2016)
```

```{r}
print(Model_g_Ltr_t0i_2016, digits = 3)
traceplot(Model_g_Ltr_t0i_2016, ask =FALSE)
autocorr.plot(Model_g_Ltr_t0i_2016)

param <- data.frame(rbind(as.mcmc(Model_g_Ltr_t0i_2016)[[1]],as.mcmc(Model_g_Ltr_t0i_2016)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")
```

```{r}
print(Model_g_Ktr_Ltr_t0i_2016, digits = 3)
traceplot(Model_g_Ktr_Ltr_t0i_2016, ask =FALSE)
autocorr.plot(Model_g_Ktr_Ltr_t0i_2016)

param <- data.frame(rbind(as.mcmc(Model_g_Ktr_Ltr_t0i_2016)[[1]],as.mcmc(Model_g_Ktr_Ltr_t0i_2016)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")
ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.2.), color = "blue")+
  geom_density(aes(x = K.3.), color = "green")+
  geom_density(aes(x = K.4.), color = "black")

ggplot()+
  geom_point(aes(x = 1:8, y = 0.8*176*exp(-0.8*(1:8+1.3))), color = "red")+
  geom_point(aes(x = 1:8, y = 1*172.5*exp(-1*(1:8+1.3))), color = "blue")+
  geom_point(aes(x = 1:8, y = 1.1*160*exp(-1.1*(1:8+1.3))), color = "green")+
  geom_point(aes(x = 1:8, y = 1*166*exp(-1*(1:8+1.3))))
```

```{r}
print(Model_g_Ktrla_Ltrla_t0i_2016, digits = 3)
traceplot(Model_g_Ktrla_Ltrla_t0i_2016, ask =FALSE)
autocorr.plot(Model_g_Ktrla_Ltrla_t0i_2016)

param <- data.frame(rbind(as.mcmc(Model_g_Ktrla_Ltrla_t0i_2016)[[1]],as.mcmc(Model_g_Ktrla_Ltrla_t0i_2016)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")
ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.2.), color = "blue")+
  geom_density(aes(x = K.3.), color = "green")+
  geom_density(aes(x = K.4.), color = "black")

K = Model_g_Ktr_Ltr_t0i_2016[[2]]$mean$K
Linf = Model_g_Ktr_Ltr_t0i_2016[[2]]$mean$Linf

ggplot()+
  geom_point(aes(x = 1:8, y = K[1]*Linf[1]*exp(-K[1]*(1:8+1.3))), color = "red")+
  geom_point(aes(x = 1:8, y = K[2]*Linf[2]*exp(-K[2]*(1:8+1.3))), color = "blue")+
  geom_point(aes(x = 1:8, y = K[3]*Linf[3]*exp(-K[3]*(1:8+1.3))), color = "green")+
  geom_point(aes(x = 1:8, y = K[4]*Linf[4]*exp(-K[4]*(1:8+1.3))))

ggplot(param)+
  geom_density(aes(x = Linfla.1.), color = "red")+
  geom_density(aes(x = Linfla.8.), color = "red")+
  geom_density(aes(x = Linfla.3.), color = "red")+
  geom_density(aes(x = Linfla.6.), color = "red")+
  geom_density(aes(x = Linfla.11.), color = "blue")+
  geom_density(aes(x = Linfla.14.), color = "blue")+
  geom_density(aes(x = Linfla.9.), color = "blue")+
  geom_density(aes(x = Linfla.16.), color = "blue")+
  geom_density(aes(x = Linfla.2.), color = "green")+
  geom_density(aes(x = Linfla.7.), color = "green")+
  geom_density(aes(x = Linfla.4.), color = "green")+
  geom_density(aes(x = Linfla.5.), color = "green")+
  geom_density(aes(x = Linfla.12.), color = "black")+
  geom_density(aes(x = Linfla.13.), color = "black")+
  geom_density(aes(x = Linfla.10.), color = "black")+
  geom_density(aes(x = Linfla.15.), color = "black")


ggplot(param)+
  geom_density(aes(x = Kla.1.), color = "red")+
  geom_density(aes(x = Kla.8.), color = "red")+
  geom_density(aes(x = Kla.3.), color = "red")+
  geom_density(aes(x = Kla.6.), color = "red")+
  geom_density(aes(x = Kla.11.), color = "blue")+
  geom_density(aes(x = Kla.14.), color = "blue")+
  geom_density(aes(x = Kla.9.), color = "blue")+
  geom_density(aes(x = Kla.16.), color = "blue")+
  geom_density(aes(x = Kla.2.), color = "green")+
  geom_density(aes(x = Kla.7.), color = "green")+
  geom_density(aes(x = Kla.4.), color = "green")+
  geom_density(aes(x = Kla.5.), color = "green")+
  geom_density(aes(x = Kla.12.), color = "black")+
  geom_density(aes(x = Kla.13.), color = "black")+
  geom_density(aes(x = Kla.10.), color = "black")+
  geom_density(aes(x = Kla.15.), color = "black")

```

```{r}
print(Model_g_Ktrla_Ltrla_2016, digits = 3)
traceplot(Model_g_Ktrla_Ltrla_2016, ask =FALSE) #varname = c("pKla", "pLinfla"),
#autocorr.plot(Model_g_Ktrla_Ltrla_2016, c("pKla"))

param <- data.frame(rbind(as.mcmc(Model_g_Ktrla_Ltrla_2016)[[1]],as.mcmc(Model_g_Ktrla_Ltrla_2016)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")
ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.2.), color = "blue")+
  geom_density(aes(x = K.3.), color = "green")+
  geom_density(aes(x = K.4.), color = "black")

K = Model_g_Ktrla_Ltrla_2016[[2]]$mean$K
Linf = Model_g_Ktrla_Ltrla_2016[[2]]$mean$Linf

ggplot()+
  geom_point(aes(x = 1:8, y = K[1]*Linf[1]*exp(-K[1]*(1:8+1.3))), color = "red")+
  geom_point(aes(x = 1:8, y = K[2]*Linf[2]*exp(-K[2]*(1:8+1.3))), color = "blue")+
  geom_point(aes(x = 1:8, y = K[3]*Linf[3]*exp(-K[3]*(1:8+1.3))), color = "green")+
  geom_point(aes(x = 1:8, y = K[4]*Linf[4]*exp(-K[4]*(1:8+1.3))))

ggplot(param)+
  geom_density(aes(x = Linfla.1.), color = "red")+
  geom_density(aes(x = Linfla.8.), color = "red")+
  geom_density(aes(x = Linfla.3.), color = "red")+
  geom_density(aes(x = Linfla.6.), color = "red")+
  geom_density(aes(x = Linfla.11.), color = "blue")+
  geom_density(aes(x = Linfla.14.), color = "blue")+
  geom_density(aes(x = Linfla.9.), color = "blue")+
  geom_density(aes(x = Linfla.16.), color = "blue")+
  geom_density(aes(x = Linfla.2.), color = "green")+
  geom_density(aes(x = Linfla.7.), color = "green")+
  geom_density(aes(x = Linfla.4.), color = "green")+
  geom_density(aes(x = Linfla.5.), color = "green")+
  geom_density(aes(x = Linfla.12.), color = "black")+
  geom_density(aes(x = Linfla.13.), color = "black")+
  geom_density(aes(x = Linfla.10.), color = "black")+
  geom_density(aes(x = Linfla.15.), color = "black")
  

ggplot(param)+
  geom_density(aes(x = Kla.1.), color = "red")+
  geom_density(aes(x = Kla.8.), color = "red")+
  geom_density(aes(x = Kla.3.), color = "red")+
  geom_density(aes(x = Kla.6.), color = "red")+
  geom_density(aes(x = Kla.11.), color = "blue")+
  geom_density(aes(x = Kla.14.), color = "blue")+
  geom_density(aes(x = Kla.9.), color = "blue")+
  geom_density(aes(x = Kla.16.), color = "blue")+
  geom_density(aes(x = Kla.2.), color = "green")+
  geom_density(aes(x = Kla.7.), color = "green")+
  geom_density(aes(x = Kla.4.), color = "green")+
  geom_density(aes(x = Kla.5.), color = "green")+
  geom_density(aes(x = Kla.12.), color = "black")+
  geom_density(aes(x = Kla.13.), color = "black")+
  geom_density(aes(x = Kla.10.), color = "black")+
  geom_density(aes(x = Kla.15.), color = "black")
```

```{r}
print(Model_g_Ktr_Ltr_2016, digits = 3)
traceplot(Model_g_Ktr_Ltr_2016, ask =FALSE)
autocorr.plot(Model_g_Ktr_Ltr_2016)

param <- data.frame(rbind(as.mcmc(Model_g_Ktr_Ltr_2016)[[1]],as.mcmc(Model_g_Ktr_Ltr_2016)[[2]]))
ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.2.), color = "blue")+
  geom_density(aes(x = Linf.3.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "black")
ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.2.), color = "blue")+
  geom_density(aes(x = K.3.), color = "green")+
  geom_density(aes(x = K.4.), color = "black")

K = Model_g_Ktr_Ltr_2016[[2]]$mean$K
Linf = Model_g_Ktr_Ltr_2016[[2]]$mean$Linf

ggplot()+
  geom_point(aes(x = 1:8, y = K[1]*Linf[1]*exp(-K[1]*(1:8+1.3))), color = "red")+
  geom_point(aes(x = 1:8, y = K[2]*Linf[2]*exp(-K[2]*(1:8+1.3))), color = "blue")+
  geom_point(aes(x = 1:8, y = K[3]*Linf[3]*exp(-K[3]*(1:8+1.3))), color = "green")+
  geom_point(aes(x = 1:8, y = K[4]*Linf[4]*exp(-K[4]*(1:8+1.3))))
```

```{r}
print(Model_g_Kla_Lla_2016, digits = 3)
#traceplot(Model_g_Kla_Lla_2016, varname = c(),ask =FALSE)
#autocorr.plot(Model_g_Ktrla_Ltrla_2016, c("pKla"))

param <- data.frame(rbind(as.mcmc(Model_g_Kla_Lla_2016)[[1]],as.mcmc(Model_g_Kla_Lla_2016)[[2]]))

ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.8.), color = "red")+
  geom_density(aes(x = Linf.3.), color = "red")+
  geom_density(aes(x = Linf.6.), color = "red")+
  geom_density(aes(x = Linf.11.), color = "blue")+
  geom_density(aes(x = Linf.14.), color = "blue")+
  geom_density(aes(x = Linf.9.), color = "blue")+
  geom_density(aes(x = Linf.16.), color = "blue")+
  geom_density(aes(x = Linf.2.), color = "green")+
  geom_density(aes(x = Linf.7.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "green")+
  geom_density(aes(x = Linf.5.), color = "green")+
  geom_density(aes(x = Linf.12.), color = "black")+
  geom_density(aes(x = Linf.13.), color = "black")+
  geom_density(aes(x = Linf.10.), color = "black")+
  geom_density(aes(x = Linf.15.), color = "black")
  

ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.8.), color = "red")+
  geom_density(aes(x = K.3.), color = "red")+
  geom_density(aes(x = K.6.), color = "red")+
  geom_density(aes(x = K.11.), color = "blue")+
  geom_density(aes(x = K.14.), color = "blue")+
  geom_density(aes(x = K.9.), color = "blue")+
  geom_density(aes(x = K.16.), color = "blue")+
  geom_density(aes(x = K.2.), color = "green")+
  geom_density(aes(x = K.7.), color = "green")+
  geom_density(aes(x = K.4.), color = "green")+
  geom_density(aes(x = K.5.), color = "green")+
  geom_density(aes(x = K.12.), color = "black")+
  geom_density(aes(x = K.13.), color = "black")+
  geom_density(aes(x = K.10.), color = "black")+
  geom_density(aes(x = K.15.), color = "black")
```

# Tous les DIC des models sur 2016
```{r}

# le danger c'est que j'ai fait tourner ceux sans la avec les poissons qui ont changés de lac mais pas de traitement donc ça peut modifier le R2 (l'augmenter plutôt) ça c'est réglé
# maintenant comment est-ce qu'il prends en compte les effecte random et les autres ?

dic = c()
for (model in list_model){
  dic <- append(dic, model[[2]]$DIC)
}
DIC <- data.frame(nom_model, variable_model, dic)

colnames(DIC) <- c("model", "variable","dic")

DIC
```


```{r}
rjags::load.module('dic')
WAIC = data.frame()
for (Model in list_model){
recompile(Model)
samples <- jags.samples(Model$model[[1]], c("WAIC", "deviance"), type = "mean", n.iter = 200)

samples$p_waic <- samples$WAIC
samples$waic <- samples$deviance + samples$p_waic
tmp <- sapply(samples, sum)
waic <- round(c(waic = tmp[["waic"]], 
                p_waic = tmp[["p_waic"]]),1)
WAIC <- rbind (WAIC,waic)}

colnames(WAIC) <- c("waic", "p_waic")

DIC_WAIC <- cbind (DIC,WAIC)
DIC_WAIC %>% arrange(waic)
```

```{r}
DIC_WAIC %>% arrange(dic)
```

```{r}
data.frame(Model_g_Kla_Lla_2016[[2]]$mean, Model_g_Kla_Lla_t0i_2016[[2]]$mean)

param <- data.frame(rbind(as.mcmc(Model_g_Kla_Lla_2016)[[1]],as.mcmc(Model_g_Kla_Lla_2016)[[2]],as.mcmc(Model_g_Kla_Lla_2016)[[3]],as.mcmc(Model_g_Kla_Lla_2016)[[4]]))

ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.8.), color = "red")+
  geom_density(aes(x = Linf.3.), color = "red")+
  geom_density(aes(x = Linf.6.), color = "red")+
  geom_density(aes(x = Linf.11.), color = "blue")+
  geom_density(aes(x = Linf.14.), color = "blue")+
  geom_density(aes(x = Linf.9.), color = "blue")+
  geom_density(aes(x = Linf.16.), color = "blue")+
  geom_density(aes(x = Linf.2.), color = "green")+
  geom_density(aes(x = Linf.7.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "green")+
  geom_density(aes(x = Linf.5.), color = "green")+
  geom_density(aes(x = Linf.12.), color = "black")+
  geom_density(aes(x = Linf.13.), color = "black")+
  geom_density(aes(x = Linf.10.), color = "black")+
  geom_density(aes(x = Linf.15.), color = "black")
  

ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.8.), color = "red")+
  geom_density(aes(x = K.3.), color = "red")+
  geom_density(aes(x = K.6.), color = "red")+
  geom_density(aes(x = K.11.), color = "blue")+
  geom_density(aes(x = K.14.), color = "blue")+
  geom_density(aes(x = K.9.), color = "blue")+
  geom_density(aes(x = K.16.), color = "blue")+
  geom_density(aes(x = K.2.), color = "green")+
  geom_density(aes(x = K.7.), color = "green")+
  geom_density(aes(x = K.4.), color = "green")+
  geom_density(aes(x = K.5.), color = "green")+
  geom_density(aes(x = K.12.), color = "black")+
  geom_density(aes(x = K.13.), color = "black")+
  geom_density(aes(x = K.10.), color = "black")+
  geom_density(aes(x = K.15.), color = "black")

param <- data.frame(rbind(as.mcmc(Model_g_Kla_Lla_t0i_2016)[[1]],as.mcmc(Model_g_Kla_Lla_t0i_2016)[[2]],as.mcmc(Model_g_Kla_Lla_t0i_2016)[[3]],as.mcmc(Model_g_Kla_Lla_t0i_2016)[[4]]))

ggplot(param)+
  geom_density(aes(x = Linf.1.), color = "red")+
  geom_density(aes(x = Linf.8.), color = "red")+
  geom_density(aes(x = Linf.3.), color = "red")+
  geom_density(aes(x = Linf.6.), color = "red")+
  geom_density(aes(x = Linf.11.), color = "blue")+
  geom_density(aes(x = Linf.14.), color = "blue")+
  geom_density(aes(x = Linf.9.), color = "blue")+
  geom_density(aes(x = Linf.16.), color = "blue")+
  geom_density(aes(x = Linf.2.), color = "green")+
  geom_density(aes(x = Linf.7.), color = "green")+
  geom_density(aes(x = Linf.4.), color = "green")+
  geom_density(aes(x = Linf.5.), color = "green")+
  geom_density(aes(x = Linf.12.), color = "black")+
  geom_density(aes(x = Linf.13.), color = "black")+
  geom_density(aes(x = Linf.10.), color = "black")+
  geom_density(aes(x = Linf.15.), color = "black")
  

ggplot(param)+
  geom_density(aes(x = K.1.), color = "red")+
  geom_density(aes(x = K.8.), color = "red")+
  geom_density(aes(x = K.3.), color = "red")+
  geom_density(aes(x = K.6.), color = "red")+
  geom_density(aes(x = K.11.), color = "blue")+
  geom_density(aes(x = K.14.), color = "blue")+
  geom_density(aes(x = K.9.), color = "blue")+
  geom_density(aes(x = K.16.), color = "blue")+
  geom_density(aes(x = K.2.), color = "green")+
  geom_density(aes(x = K.7.), color = "green")+
  geom_density(aes(x = K.4.), color = "green")+
  geom_density(aes(x = K.5.), color = "green")+
  geom_density(aes(x = K.12.), color = "black")+
  geom_density(aes(x = K.13.), color = "black")+
  geom_density(aes(x = K.10.), color = "black")+
  geom_density(aes(x = K.15.), color = "black")
```
```{r}
t0 = 2015 - Model_g_Kla_Lla_2016[[2]]$mean$t0

K = Model_g_Kla_Lla_2016[[2]]$mean$K
Linf = Model_g_Kla_Lla_2016[[2]]$mean$Linf


predict <- rbind(data.frame(x = 1:8, y = -30 +Linf[1]*(1-exp(-K[1]*(1:8+t0))), Lake = "1"),
                 data.frame(x = 1:8, y = Linf[2]*(1-exp(-K[2]*(1:8+t0))), Lake = "2"),
                 data.frame(x = 1:8, y = Linf[3]*(1-exp(-K[3]*(1:8+t0))), Lake = "3"),
                 data.frame(x = 1:8, y = Linf[4]*(1-exp(-K[4]*(1:8+t0))), Lake = "4"),
                 data.frame(x = 1:8, y = Linf[8]*(1-exp(-K[8]*(1:8+t0))), Lake = "8"),
                 data.frame(x = 1:8, y = Linf[7]*(1-exp(-K[7]*(1:8+t0))), Lake = "7"),
                 data.frame(x = 1:8, y = Linf[6]*(1-exp(-K[6]*(1:8+t0))), Lake = "6"),
                 data.frame(x = 1:8, y = Linf[5]*(1-exp(-K[5]*(1:8+t0))), Lake = "5"),
                 data.frame(x = 1:8, y = Linf[11]*(1-exp(-K[11]*(1:8+t0))), Lake = "11"),
                 data.frame(x = 1:8, y = Linf[12]*(1-exp(-K[12]*(1:8+t0))), Lake = "12"),
                 data.frame(x = 1:8, y = Linf[9]*(1-exp(-K[9]*(1:8+t0))), Lake = "9") ,
                 data.frame(x = 1:8, y = Linf[10]*(1-exp(-K[10]*(1:8+t0))), Lake = "10"),
                 data.frame(x = 1:8, y = Linf[14]*(1-exp(-K[14]*(1:8+t0))), Lake = "14"),
                 data.frame(x = 1:8, y = Linf[13]*(1-exp(-K[13]*(1:8+t0))), Lake = "13"),
                 data.frame(x = 1:8, y = Linf[16]*(1-exp(-K[16]*(1:8+t0))), Lake = "16"),
                 data.frame(x = 1:8, y = Linf[15]*(1-exp(-K[15]*(1:8+t0))), Lake = "15"))

ggplot(BDD_a %>% filter (Tag_year == "2016"), aes (x = Year, y = Size))+
  geom_line(aes(group = Tag_id, color = Lake))+
  geom_point(data = predict, aes(x = x, y = y))+
  facet_wrap(~ factor(Lake, c(1,8,3,6,11,14,9,16,2,7,4,5,12,13,10,15)))+
  labs(title = "Model_g_Kla_Lla_2016")

t0 = 1.5

K = Model_g_Kla_Lla_t0i_2016[[2]]$mean$K
Linf = Model_g_Kla_Lla_t0i_2016[[2]]$mean$Linf

predict <- rbind(data.frame(x = 1:8, y = -30+ Linf[1]*(1-exp(-K[1]*(1:8+t0))), Lake = "1"),
                 data.frame(x = 1:8, y = Linf[2]*(1-exp(-K[2]*(1:8+t0))), Lake = "2"),
                 data.frame(x = 1:8, y = Linf[3]*(1-exp(-K[3]*(1:8+t0))), Lake = "3"),
                 data.frame(x = 1:8, y = Linf[4]*(1-exp(-K[4]*(1:8+t0))), Lake = "4"),
                 data.frame(x = 1:8, y = Linf[8]*(1-exp(-K[8]*(1:8+t0))), Lake = "8"),
                 data.frame(x = 1:8, y = Linf[7]*(1-exp(-K[7]*(1:8+t0))), Lake = "7"),
                 data.frame(x = 1:8, y = Linf[6]*(1-exp(-K[6]*(1:8+t0))), Lake = "6"),
                 data.frame(x = 1:8, y = Linf[5]*(1-exp(-K[5]*(1:8+t0))), Lake = "5"),
                 data.frame(x = 1:8, y = Linf[11]*(1-exp(-K[11]*(1:8+t0))), Lake = "11"),
                 data.frame(x = 1:8, y = Linf[12]*(1-exp(-K[12]*(1:8+t0))), Lake = "12"),
                 data.frame(x = 1:8, y = Linf[9]*(1-exp(-K[9]*(1:8+t0))), Lake = "9") ,
                 data.frame(x = 1:8, y = Linf[10]*(1-exp(-K[10]*(1:8+t0))), Lake = "10"),
                 data.frame(x = 1:8, y = Linf[14]*(1-exp(-K[14]*(1:8+t0))), Lake = "14"),
                 data.frame(x = 1:8, y = Linf[13]*(1-exp(-K[13]*(1:8+t0))), Lake = "13"),
                 data.frame(x = 1:8, y = Linf[16]*(1-exp(-K[16]*(1:8+t0))), Lake = "16"),
                 data.frame(x = 1:8, y = Linf[15]*(1-exp(-K[15]*(1:8+t0))), Lake = "15"))

ggplot(BDD_a %>% filter (Tag_year == "2016"), aes (x = Year, y = Size))+
  geom_line(aes(group = Tag_id, color = Lake))+
  geom_point(data = predict, aes(x = x, y = y))+
  facet_wrap(~ factor(Lake, c(1,8,3,6,11,14,9,16,2,7,4,5,12,13,10,15)))+
  labs(title = "Model_g_Kla_Lla_t0i_2016")


#ggplot()+
#  geom_point(aes(x = 1:8, y = K[1]*Linf[1]*exp(-K[1]*(1:8+1.3))), color = "red")+
#  geom_point(aes(x = 1:8, y = K[2]*Linf[2]*exp(-K[2]*(1:8+1.3))), color = "blue")+
#  geom_point(aes(x = 1:8, y = K[3]*Linf[3]*exp(-K[3]*(1:8+1.3))), color = "green")+
#  geom_point(aes(x = 1:8, y = K[4]*Linf[4]*exp(-K[4]*(1:8+1.3))), color = "black")+
#  geom_point(aes(x = 1:8, y = K[8]*Linf[8]*exp(-K[8]*(1:8+1.3))), color = "red")+
#  geom_point(aes(x = 1:8, y = K[7]*Linf[7]*exp(-K[7]*(1:8+1.3))), color = "blue")+
#  geom_point(aes(x = 1:8, y = K[6]*Linf[6]*exp(-K[6]*(1:8+1.3))), color = "green")+
#  geom_point(aes(x = 1:8, y = K[5]*Linf[5]*exp(-K[5]*(1:8+1.3))), color = "black")+
#  geom_point(aes(x = 1:8, y = K[11]*Linf[11]*exp(-K[11]*(1:8+1.3))), color = "red")+
#  geom_point(aes(x = 1:8, y = K[12]*Linf[12]*exp(-K[12]*(1:8+1.3))), color = "blue")+
#  geom_point(aes(x = 1:8, y = K[9]*Linf[9]*exp(-K[9]*(1:8+1.3))), color = "green")+
#  geom_point(aes(x = 1:8, y = K[10]*Linf[10]*exp(-K[10]*(1:8+1.3))), color = "black")+
#  geom_point(aes(x = 1:8, y = K[14]*Linf[14]*exp(-K[14]*(1:8+1.3))), color = "red")+
#  geom_point(aes(x = 1:8, y = K[13]*Linf[13]*exp(-K[13]*(1:8+1.3))), color = "blue")+
#  geom_point(aes(x = 1:8, y = K[16]*Linf[16]*exp(-K[16]*(1:8+1.3))), color = "green")+
#  geom_point(aes(x = 1:8, y = K[15]*Linf[15]*exp(-K[15]*(1:8+1.3))), color = "black")
#
#ggplot()+
#  geom_point(aes(x = 1:8, y = Linf[1]*(1-exp(-K[1]*(1:8+1.3)))), color = "red")+
#  geom_point(aes(x = 1:8, y = Linf[2]*(1-exp(-K[2]*(1:8+1.3)))), color = "blue")+
#  geom_point(aes(x = 1:8, y = Linf[3]*(1-exp(-K[3]*(1:8+1.3)))), color = "green")+
#  geom_point(aes(x = 1:8, y = Linf[4]*(1-exp(-K[4]*(1:8+1.3)))), color = "black")+
#  geom_point(aes(x = 1:8, y = Linf[8]*(1-exp(-K[8]*(1:8+1.3)))), color = "red")+
#  geom_point(aes(x = 1:8, y = Linf[7]*(1-exp(-K[7]*(1:8+1.3)))), color = "blue")+
#  geom_point(aes(x = 1:8, y = Linf[6]*(1-exp(-K[6]*(1:8+1.3)))), color = "green")+
#  geom_point(aes(x = 1:8, y = Linf[5]*(1-exp(-K[5]*(1:8+1.3)))), color = "black")+
#  geom_point(aes(x = 1:8, y = Linf[11]*(1-exp(-K[11]*(1:8+1.3)))), color = "red")+
#  geom_point(aes(x = 1:8, y = Linf[12]*(1-exp(-K[12]*(1:8+1.3)))), color = "blue")+
#  geom_point(aes(x = 1:8, y = Linf[9]*(1-exp(-K[9]*(1:8+1.3)))), color = "green")+
#  geom_point(aes(x = 1:8, y = Linf[10]*(1-exp(-K[10]*(1:8+1.3)))), color = "black")+
#  geom_point(aes(x = 1:8, y = Linf[14]*(1-exp(-K[14]*(1:8+1.3)))), color = "red")+
#  geom_point(aes(x = 1:8, y = Linf[13]*(1-exp(-K[13]*(1:8+1.3)))), color = "blue")+
#  geom_point(aes(x = 1:8, y = Linf[16]*(1-exp(-K[16]*(1:8+1.3)))), color = "green")+
#  geom_point(aes(x = 1:8, y = Linf[15]*(1-exp(-K[15]*(1:8+1.3)))), color = "black")


```

```{r}
ggplot(BDD_a %>% filter(Tag_year == "2016" & Year == "2022"))+
  geom_density(aes(x = Size, color = Treatment))
```

```{r}
# remplissage du tableau des tailles
# création d'un tableau d'augmentation de taille par lac et année
tbl = data.frame()
t0 <- Model_g_Kla_Lla_2016[[2]]$mean$t0
for (i in 1:16){
  K <- Model_g_Kla_Lla_2016[[2]]$mean$K[i]
  Linf <- Model_g_Kla_Lla_2016[[2]]$mean$Linf[i]
    
  for (t in 2017:2021){
    tbl <- rbind(tbl, data.frame(i,t,Linf*(1-exp(-K*(t-t0)))-Linf*(1-exp(-K*(t-1-t0)))))
  }
}
colnames(tbl) <- c("Lake", "Year", "Size")
tbl <- tbl %>% mutate(Lake = factor(Lake), Year = factor(Year))
head(tbl)

ggplot(tbl)+
  geom_point(aes(x = Year, y = Size))+
  facet_wrap(~ Lake)

# Maintenant remplissage
tr <- BDD_a %>% group_by(Tag_id, Treatment) %>% summarize() %>% ungroup()
mooved <- tr[duplicated(tr$Tag_id),]$Tag_id
tr <- tr %>% filter ( !duplicated(tr$Tag_id))
tr <- tr %>% mutate (Treatment = ifelse(Tag_id %in% mooved, NA, Treatment))

la <- BDD_a %>% group_by(Tag_id, Lake) %>% summarize() %>% ungroup()
mooved <- la[duplicated(la$Tag_id),]$Tag_id
la <- la %>% filter ( !duplicated(la$Tag_id))
la <- la %>% mutate (Lake = ifelse(Tag_id %in% mooved, NA, Lake))

s <- BDD_a %>% ungroup () %>% pivot_wider(id_cols = Tag_id, names_from = Year, values_from = Size)
s <- s %>% merge(la) %>% merge(tr)



head(s)

get.first <- function(x) min(which(!is.na(x)))
f <- apply(s[2:8], 1, get.first)

for (i in 1:nrow(s)){
  if (!is.na(s$Lake[i])){
    t0 <- f[i]+1
    if (t0 <7){
      for (t in (t0+1):7){ # ou 7 je ne sais pas encore comment je preends en comte 2022
        if (is.na(s[i,t])){
          s[i,t] <- s[i,t-1] + subset(tbl, Lake == s$Lake[i] & Year == 2015+t-f[i])$Size
        }
      }
    }
    if (is.na(s[i,8])){s[i,8] <- s[i,7]}
  }
}

s

```

```{r}
s_bis <- s %>% pivot_longer(cols = 2:8) %>% na.omit() %>% mutate (Lake = factor(Lake))

ggplot(s_bis)+
  geom_line(aes(x = name, y = value, group = Tag_id, color = Lake))+
  facet_wrap(~Lake)

ggplot(BDD_a)+
  geom_line(aes(x = Year, y = Size, group = Tag_id, color = Lake))+
  facet_wrap(~Lake)
```

