---
title: "R Notebook"
output: 
---

```{r}
print(CJS_0)
autocorr.plot(CJS_0, ask = F)
traceplot(CJS_0, ask = F)
```

```{r}
print(CJS_1)
autocorr.plot(CJS_1, ask = F)
traceplot(CJS_1, ask = F)
```


```{r}
print(CJS_treatment)
autocorr.plot(CJS_treatment, ask = F)
traceplot(CJS_treatment, ask = F)
```

```{r}
print(CJS_treatment_age)
autocorr.plot(CJS_treatment_age, ask = F)
traceplot(CJS_treatment_age, ask = F)
```
```{r}

tbl = data.frame()
for (i in 1:4){
  for (j in 1:6){
    x = as.mcmc(CJS_treatment_age)[[1]][,paste("phi[", as.character(i), ",", as.character(j), "]", sep = "")]
    tbl <- rbind(tbl,data.frame(x,i,j))
  }
}

colnames(tbl) <- c("phi","Treatment","Age")
tbl <- tbl %>% mutate(Treatment = factor(Treatment)) %>% mutate(Age = factor(Age))

ggplot(tbl)+
  geom_density(aes( x = phi, color = Treatment))+
  facet_wrap(~ Age)

ggplot(tbl)+
  geom_boxplot(aes( y = phi, color = Age))

ggplot(tbl)+
  geom_density(aes( x = phi, color = Age))+
  facet_wrap(~ Treatment)

tbl = data.frame()
for (i in 1:5){
  x = as.mcmc(CJS_treatment_age)[[1]][,paste("p[", as.character(i),"]", sep = "")]
  tbl <- rbind(tbl,data.frame(x,i))
}

colnames(tbl) <- c("p","Age")
tbl <- tbl %>% mutate(Age = factor(Age))


ggplot(tbl)+
  geom_density(aes( x = p, color = Age))

ggplot(tbl)+
  geom_boxplot(aes(y = p, color = Age))
```


```{r}
print(CJS_treatment_maturity)
autocorr.plot(CJS_treatment_maturity, ask = F)
traceplot(CJS_treatment_maturity, ask = F)
```

```{r}
tbl = data.frame()
for (i in 1:4){
  for (j in 1:2){
    x = as.mcmc(CJS_treatment_maturity)[[1]][,paste("phim[", as.character(i), ",", as.character(j), "]", sep = "")]
    tbl <- rbind(tbl,data.frame(x,i,j))
  }
}

colnames(tbl) <- c("phi","Treatment","Maturity")
tbl <- tbl %>% mutate(Treatment = factor(Treatment)) %>% mutate(Maturity = factor(Maturity))

ggplot(tbl)+
  geom_density(aes( x = phi, color = Treatment))+
  facet_wrap(~ Maturity)

ggplot(tbl)+
  geom_density(aes( x = phi, color = Maturity))+
  facet_wrap(~ Treatment)

tbl = data.frame()
for (j in 1:2){
    x = as.mcmc(CJS_treatment_maturity)[[1]][,paste("pm[", as.character(j), "]", sep = "")]
    tbl <- rbind(tbl,data.frame(x,j))
}

colnames(tbl) <- c("p","Maturity")

tbl <- tbl %>% mutate(Maturity = factor(Maturity))

ggplot(tbl)+
  geom_density(aes( x = p, color = Maturity))

```


```{r}
print(CJS_3)
autocorr.plot(CJS_3, ask = F)
traceplot(CJS_3, ask = F)
```

```{r}
list_model = list(CJS_0,CJS_1,CJS_3, CJS_treatment, CJS_treatment_age, CJS_treatment_maturity) # CJS_taille1, CJS_taille2
nom_model = c("CJS_0","CJS_1","CJS_3", "CJS_treatment", "CJS_treatment_age", "CJS_treatment_maturity")
variable_model = c("p(~1)phi(~1)","p(~t+i)phi(~t+i)","p(~1)phi(~1)n(~t)","p(~1)phi(~tr)","p(~age)phi(~tr+age)","p(~mat)phi(~tr+mat)")
deviance = c()
dic = c()
pD = c()
for (model in list_model){
  deviance <- append(deviance, model[[2]]$mean$deviance)
  dic <- append(dic, model[[2]]$DIC)
  pD <- append(pD, model[[2]]$pD)
}
DIC <- data.frame(nom_model, deviance, variable_model, dic, pD)

colnames(DIC) <- c("model", "deviance", "variable","dic", "pD")

DIC %>% arrange(dic)
```

```{r}

rjags::load.module('dic')
WAIC = data.frame()

for (Model in list_model){
  #recompile(CJS_3)
  samples <- jags.samples(Model$model[[1]], 
                          c("WAIC", "deviance"), type ="mean", n.iter = 200)

  samples$p_waic <- samples$WAIC
  samples$waic <- samples$deviance + samples$p_waic
  tmp <- sapply(samples, sum)
  waic <- round(c(waic = tmp[["waic"]], 
                p_waic = tmp[["p_waic"]]),1)
  WAIC <- rbind (WAIC,waic)
}

colnames(WAIC) <- c("waic", "p_waic")

DIC_WAIC <- cbind (DIC,WAIC)
DIC_WAIC %>% arrange(waic)
```



############ N'importe quoi à partir d'ici


```{r}
print(CJS_taille2)
autocorr.plot(CJS_taille2, ask = F)
traceplot(CJS_taille2, ask = F)
```

```{r}
print(CJS_taille2)
autocorr.plot(CJS_taille2, ask = F)
traceplot(CJS_taille2, ask = F)
```

```{r}

taille <- BDD_a$Size
p <- 1/(1+exp(-0.003*taille))
phi <- invlogit(0.003*taille+1)
df = data.frame(taille,phi,p)

ggplot(df)+
  geom_point(aes(x = taille, y = phi))+
  geom_point(aes(x = taille, y = p), color = "red")

```


```{r}
print(CJS_0)
autocorr.plot(CJS_0, ask = F)
traceplot(CJS_0, ask = F)
```


```{r}
print(CJS_0_2022)
autocorr.plot(CJS_0_2022, ask = F)
traceplot(CJS_0_2022, ask = F)
```

```{r}
print(CJS_group_taille)
autocorr.plot(CJS_group_taille, ask = F)
traceplot(CJS_group_taille, ask = F)

tbl = data.frame()
for (i in 1:3){
  tbl <- rbind(tbl, 
               data.frame(as.mcmc(CJS_group_taille)[[1]][,paste("p[",as.character(i),"]", sep = "")],
                          as.mcmc(CJS_group_taille)[[1]][,paste("phi[",as.character(i),"]", sep = "")],
                          i))
}
colnames(tbl) <- c("p","phi","taille")
tbl <- tbl %>% mutate(taille = factor (taille))

ggplot(tbl)+
  geom_violin(aes(x = taille , y = phi, color = taille))

ggplot(tbl)+
  geom_violin(aes(x = taille , y = p, color = taille))
```

```{r}
table(unlist(s_group))
```


```{r}
print(CJS_group_taille_tr)
#autocorr.plot(CJS_group_taille_tr, ask = F)
#traceplot(CJS_group_taille_tr, ask = F)

tbl_p = data.frame()
tbl_phi = data.frame()
for (i in 1:4){
  tbl_p <- rbind(tbl_p, 
               data.frame(as.mcmc(CJS_group_taille_tr)[[1]][,paste("p[",as.character(i),"]", sep = "")],i))
  for (j in 1:4){
    tbl_phi <- rbind(tbl_phi, 
               data.frame(as.mcmc(CJS_group_taille_tr)[[1]][,paste("phi[",as.character(i),",",as.character(j),"]", sep = "")],i,j))
  }
}
colnames(tbl_phi) <- c("phi","taille","treatment")
tbl_phi <- tbl_phi %>% mutate(taille = factor (taille),
                              treatment = factor(treatment))
colnames(tbl_p) <- c("p","taille")
tbl_p <- tbl_p %>% mutate(taille = factor (taille))

head(tbl_p)
ggplot(tbl_phi)+
  geom_violin(aes(y = phi, x = treatment, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_p)+
  geom_violin(aes(x = taille , y = p, color = taille))
```

```{r}
print(CJS_group_taille_tr_p)
#autocorr.plot(CJS_group_taille_tr, ask = F)
#traceplot(CJS_group_taille_tr, ask = F)

tbl_p = data.frame()
tbl_phi = data.frame()
for (i in 1:6){
  for (t in 1:6){
    for (l in 1:16){
      tbl_p <- rbind(tbl_p, 
               data.frame(as.mcmc(CJS_group_taille_tr_p)[[1]][1:200,paste("p[",as.character(i),",",as.character(t),",",as.character(l),"]", sep = "")],i,t,l))
    }
  }
  
  for (j in 1:4){
    tbl_phi <- rbind(tbl_phi, 
               data.frame(as.mcmc(CJS_group_taille_tr_p)[[1]][1:200,paste("phi[",as.character(i),",",as.character(j),"]", sep = "")],i,j))
  }
}
colnames(tbl_phi) <- c("phi","taille","treatment")
tbl_phi <- tbl_phi %>% mutate(taille = factor (taille),
                              treatment = factor(treatment))
colnames(tbl_p) <- c("p","taille","year","Lake")
tbl_p <- tbl_p %>% mutate(taille = factor (taille),
                          year = factor(year),
                          Lake = factor(Lake))


ggplot(tbl_phi)+
  geom_boxplot(aes(y = phi, x = treatment, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_p)+
  geom_boxplot(aes(x = year , y = p))+
  facet_wrap(~Lake)
```

```{r}
print(CJS_group_taille_trt_p)
#autocorr.plot(CJS_group_taille_tr_p_t, ask = F)
#traceplot(CJS_group_taille_tr_p_t, varname = c("phi"),ask = F)

tbl_p2 = data.frame()
tbl_phi2 = data.frame()
for (i in 1:6){
  for (t in 1:5){
    for (l in 1:16){
      tbl_p2 <- rbind(tbl_p2, 
               data.frame(as.mcmc(CJS_group_taille_trt_p)[[1]][1:200,paste("p[",as.character(i),",",as.character(t),",",as.character(l),"]", sep = "")],i,t,l))
    }
  
    for (tr in 1:4){
    tbl_phi2 <- rbind(tbl_phi2, 
               data.frame(as.mcmc(CJS_group_taille_trt_p)[[1]][1:200,paste("phi[",as.character(i),",",as.character(t),",",as.character(tr),"]", sep = "")],i,t,tr))
    }
  }
}
colnames(tbl_phi2) <- c("phi","taille","year","treatment")
tbl_phi2 <- tbl_phi2 %>% mutate(taille = factor (taille),
                              treatment = factor(treatment),
                              year = factor(year))
colnames(tbl_p2) <- c("p","taille","year","Lake")
tbl_p2 <- tbl_p2 %>% mutate(taille = factor (taille),
                          year = factor(year),
                          Lake = factor(Lake))


ggplot(tbl_phi2 %>% filter(year != "1"))+
  geom_violin(aes(y = phi, x = year, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_phi2%>% filter(year %in% c("4","5","6")))+
  geom_density(aes(x = phi, color = taille))

ggplot(tbl_phi2%>% filter(year %in% c("4","5","6")))+
  geom_density(aes(x = phi, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_p2%>% filter(year != 1))+
  geom_boxplot(aes(x = year , y = p))+
  facet_wrap(~Lake)
```

```{r}
print(CJS_group_taille_trcorrect_p)
#autocorr.plot(CJS_group_taille_tr_p_t, ask = F)
#traceplot(CJS_group_taille_tr_p_t, varname = c("phi"),ask = F)

tbl_p2 = data.frame()
tbl_phi2 = data.frame()
for (i in 1:6){
  for (t in 1:5){
    for (l in 1:16){
      tbl_p2 <- rbind(tbl_p2, 
               data.frame(as.mcmc(CJS_group_taille_trcorrect_p)[[1]][1:200,paste("p[",as.character(i),",",as.character(t),",",as.character(l),"]", sep = "")],i,t,l))
    }
  
    for (tr in 1:4){
    tbl_phi2 <- rbind(tbl_phi2, 
               data.frame(as.mcmc(CJS_group_taille_trcorrect_p)[[1]][1:200,paste("phi[",as.character(i),",",as.character(t),",",as.character(tr),"]", sep = "")],i,t,tr))
    }
  }
}
colnames(tbl_phi2) <- c("phi","taille","year","treatment")
tbl_phi2 <- tbl_phi2 %>% mutate(taille = factor (taille),
                              treatment = factor(treatment),
                              year = factor(year))
colnames(tbl_p2) <- c("p","taille","year","Lake")
tbl_p2 <- tbl_p2 %>% mutate(taille = factor (taille),
                          year = factor(year),
                          Lake = factor(Lake))


ggplot(tbl_phi2)+
  geom_violin(aes(y = phi, x = year, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_phi2%>% filter(year %in% c("3","4","5")))+
  geom_density(aes(x = phi, color = taille))

ggplot(tbl_phi2%>% filter(year %in% c("3","4","5")))+
  geom_density(aes(x = phi, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_p2%>% filter(year != 1))+
  geom_boxplot(aes(x = year , y = p))+
  facet_wrap(~Lake)
```

```{r}
print(CJS_group_taille_trcorrect)
autocorr.plot(CJS_group_taille_trcorrect, ask = F)
traceplot(CJS_group_taille_trcorrect,ask = F)

tbl_p2 = data.frame()
tbl_phi2 = data.frame()
#for (n in 1:4){
for (i in 1:4){
  tbl_p2 <- rbind(tbl_p2, 
               data.frame(as.mcmc(CJS_group_taille_trcorrect)[[1]][1:100,paste("p[",as.character(i),"]", sep = "")],i))
  for (t in 1:5){
    for (tr in 1:4){
    tbl_phi2 <- rbind(tbl_phi2, 
               data.frame(as.mcmc(CJS_group_taille_trcorrect)[[1]][1:100,paste("phi[",as.character(i),",",as.character(tr),"]", sep = "")],i,tr)) #",",as.character(t),
    }
  }
}
#}
colnames(tbl_phi2) <- c("phi","taille","treatment")
tbl_phi2 <- tbl_phi2 %>% mutate(taille = factor (taille),
                              treatment = factor(treatment))
colnames(tbl_p2) <- c("p","taille")
tbl_p2 <- tbl_p2 %>% mutate(taille = factor (taille))


ggplot(tbl_phi2)+
  geom_violin(aes(y = phi, x = treatment, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_phi2)+
  geom_density(aes(x = phi, color = taille))

ggplot(tbl_phi2)+
  geom_density(aes(x = phi, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_p2)+
  geom_boxplot(aes(x = taille , y = p))
```

```{r}
print(CJS_group_taille_trtcorrect)
#autocorr.plot(CJS_group_taille_trcorrect, ask = F)
#traceplot(CJS_group_taille_trcorrect,ask = F)

tbl_p = data.frame()
tbl_phi = data.frame()
#for (n in 1:4){
for (i in 1:4){
  tbl_p <- rbind(tbl_p, 
               data.frame(as.mcmc(CJS_group_taille_trtcorrect)[[1]][1:100,paste("p[",as.character(i),"]", sep = "")],i))
  for (t in 1:5){
    for (tr in 1:4){
    tbl_phi <- rbind(tbl_phi, 
               data.frame(as.mcmc(CJS_group_taille_trtcorrect)[[1]][1:100,paste("phi[",as.character(i),",",as.character(t),",",as.character(tr),"]", sep = "")],i,t,tr)) #
    }
  }
}
#}
colnames(tbl_phi) <- c("phi","taille","year","treatment")
tbl_phi <- tbl_phi %>% mutate(taille = factor (taille),
                                year = factor(year),
                              treatment = factor(treatment))
colnames(tbl_p) <- c("p","taille")
tbl_p <- tbl_p %>% mutate(taille = factor (taille))


ggplot(tbl_phi)+
  geom_violin(aes(y = phi, x = year, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_phi)+
  geom_density(aes(x = phi, color = taille))

ggplot(tbl_phi)+
  geom_density(aes(x = phi, color = treatment))+
  facet_wrap(~taille)

ggplot(tbl_p)+
  geom_boxplot(aes(x = taille , y = p))
```

# Il reste des petites bosses peut-être à cause des différents lacs


```{r}
print(CJS_group_taille_ltcorrect)
#autocorr.plot(CJS_group_taille_trcorrect, ask = F)
#traceplot(CJS_group_taille_trcorrect,ask = F)

tbl_p3 = data.frame()
tbl_phi3 = data.frame()
#for (n in 1:4){
for (i in 1:4){
  tbl_p3 <- rbind(tbl_p3, 
               data.frame(as.mcmc(CJS_group_taille_ltcorrect)[[1]][1:50,paste("p[",as.character(i),"]", sep = "")],i))
  for (t in 1:5){
    for (tr in 1:16){
    tbl_phi3 <- rbind(tbl_phi3, 
               data.frame(as.mcmc(CJS_group_taille_ltcorrect)[[1]][1:50,paste("phi[",as.character(i),",",as.character(t),",",as.character(tr),"]", sep = "")],i,t,tr)) #
    }
  }
}
#}
colnames(tbl_phi3) <- c("phi","taille","year","lake")
tbl_phi3 <- tbl_phi3 %>% mutate(taille = factor (taille),
                                year = factor(year),
                              lake = factor(lake))
colnames(tbl_p3) <- c("p","taille")
tbl_p3 <- tbl_p3 %>% mutate(taille = factor (taille))


ggplot(tbl_phi3)+
  geom_violin(aes(y = phi, x = year, color = lake))+
  facet_wrap(~taille)

ggplot(tbl_phi3)+
  geom_density(aes(x = phi, color = taille))

ggplot(tbl_phi3)+
  geom_density(aes(x = phi, color = lake))+
  facet_wrap(~taille)

ggplot(tbl_p3)+
  geom_boxplot(aes(x = taille , y = p))
```


```{r}
ggplot(BDD_a)+
  geom_density(aes(x = Size, color = Year))+
  facet_wrap(~Tag_year)
```

```{r}
print(Taille)
traceplot(Taille, ask = F)
autocorr.plot(Taille, ask = F)
```

```{r}
ggplot(BDD_a %>% filter (Year == "2022"))+
  geom_density(aes(x = Size, color = Treatment))
```

```{r}
print(Model_multi)
traceplot(Model_multi, ask = F)
autocorr.plot(Model_multi, ask = F)
```

```{r}
print(Model_multi_treatment)
traceplot(Model_multi_treatment, ask = F)
autocorr.plot(Model_multi_treatment, ask = F)
```

```{r}
print(Model_multi_treatment_time)
traceplot(Model_multi_treatment_time, ask = F)
autocorr.plot(Model_multi_treatment_time, ask = F)
```

```{r}
tbl1_p = data.frame()
tbl1_phi = data.frame()
tbl1_psi12 = data.frame()
#tbl1_psi23 = data.frame()
for (n in 1:2){
  tbl1_psi12 <- rbind(tbl1_psi12, 
               data.frame(as.mcmc(Model_multi)[[n]][,"psi12"]))
  #tbl1_psi23 <- rbind(tbl1_psi23, 
  #             data.frame(as.mcmc(Model_multi)[[n]][,"psi23"]))
  for (gs in 1:3){
    tbl1_p <- rbind(tbl1_p, 
               data.frame(as.mcmc(Model_multi)[[n]][,paste("p",as.character(gs), sep = "")],gs))
    tbl1_phi <- rbind(tbl1_phi, 
               data.frame(as.mcmc(Model_multi)[[n]][,paste("phi",as.character(gs), sep = "")],gs))
  }
}

colnames(tbl1_phi) <- c("phi","size")
tbl1_phi <- tbl1_phi %>% mutate(size = factor (size))

colnames(tbl1_p) <- c("p","size")
tbl1_p <- tbl1_p %>% mutate(size = factor (size))

colnames(tbl1_psi12) <- c("psi12")
#colnames(tbl1_psi23) <- c("psi23")

ggplot(tbl1_phi)+
  geom_density(aes(x = phi, color = size))

ggplot(tbl1_p)+
  geom_density(aes(x = p, color = size))
```

```{r}
tbl2_p = data.frame()
tbl2_phi = data.frame()
tbl2_psi12 = data.frame()
tbl2_psi23 = data.frame()
for (n in 1:2){
  for (tr in 1:4){
    tbl2_psi12 <- rbind(tbl2_psi12, 
               data.frame(as.mcmc(Model_multi_treatment)[[n]][,paste("psi12","[",as.character(tr),"]", sep = "")],tr))
    tbl2_psi23 <- rbind(tbl2_psi23, 
               data.frame(as.mcmc(Model_multi_treatment)[[n]][,paste("psi23","[",as.character(tr),"]", sep = "")],tr))
    for (gs in 1:3){
      tbl2_phi <- rbind(tbl2_phi, 
               data.frame(as.mcmc(Model_multi_treatment)[[n]][,paste("phi",as.character(gs),"[",as.character(tr),"]", sep = "")],gs,tr))
    }
  }
  for (gs in 1:3){
    tbl2_p <- rbind(tbl2_p, 
               data.frame(as.mcmc(Model_multi_treatment)[[n]][,paste("p",as.character(gs), sep = "")],gs))
  }
}

colnames(tbl2_phi) <- c("phi","size","treatment")
tbl2_phi <- tbl2_phi %>% mutate(size = factor (size),
                                treatment = factor(treatment))

colnames(tbl2_p) <- c("p","size")
tbl2_p <- tbl2_p %>% mutate(size = factor (size))

colnames(tbl2_psi12) <- c("psi","treatment")
tbl2_psi12 <- tbl2_psi12 %>% mutate(treatment = factor (treatment))
colnames(tbl2_psi23) <- c("psi","treatment")
tbl2_psi23 <- tbl2_psi23 %>% mutate(treatment = factor (treatment))

ggplot(tbl2_phi)+
  geom_density(aes(x = phi, color = treatment))+
  facet_wrap (~ size)

ggplot(tbl2_p)+
  geom_density(aes(x = p, color = size))

ggplot(tbl2_psi12)+
  geom_density(aes (x = psi, color = treatment))

ggplot(tbl2_psi23)+
  geom_density(aes (x = psi, color = treatment))
```

```{r}
tbl3_p = data.frame()
tbl3_phi = data.frame()
tbl3_psi12 = data.frame()
tbl3_psi23 = data.frame()
for (n in 1:2){
  for (tr in 1:4){
    for (t in 1:5){
      tbl3_psi12 <- rbind(tbl3_psi12, 
               data.frame(as.mcmc(Model_multi_treatment_time)[[n]][,paste("psi12","[",as.character(tr),",",as.character(t),"]", sep = "")],tr,t))
      tbl3_psi23 <- rbind(tbl3_psi23, 
               data.frame(as.mcmc(Model_multi_treatment_time)[[n]][,paste("psi23","[",as.character(tr),",",as.character(t),"]", sep = "")],tr,t))
    
      for (gs in 1:3){
        tbl3_phi <- rbind(tbl3_phi, 
               data.frame(as.mcmc(Model_multi_treatment_time)[[n]][,paste("phi",as.character(gs),"[",as.character(tr),",",as.character(t),"]", sep = "")],gs,tr,t))
      }
    }
  }
  for (gs in 1:3){
    tbl3_p <- rbind(tbl3_p, 
               data.frame(as.mcmc(Model_multi_treatment_time)[[n]][,paste("p",as.character(gs), sep = "")],gs))
  }
}

colnames(tbl3_phi) <- c("phi","size","treatment","year")
tbl3_phi <- tbl3_phi %>% mutate(size = factor (size),
                                treatment = factor(treatment),
                                year = factor(year))

colnames(tbl3_p) <- c("p","size")
tbl3_p <- tbl3_p %>% mutate(size = factor (size))

colnames(tbl3_psi12) <- c("psi","treatment","year")
tbl3_psi12 <- tbl3_psi12 %>% mutate(treatment = factor (treatment),
                                year = factor(year))
colnames(tbl3_psi23) <- c("psi","treatment","year")
tbl3_psi23 <- tbl3_psi23 %>% mutate(treatment = factor (treatment),
                                year = factor(year))

ggplot(tbl3_phi %>% filter(size == "1"))+
  geom_density(aes(x = phi, color = year))+
  facet_wrap(~treatment)

ggplot(tbl3_phi %>% filter(size == "2"))+
  geom_density(aes(x = phi, color = year))+
  facet_wrap(~treatment)

ggplot(tbl3_phi %>% filter(size == "3"))+
  geom_density(aes(x = phi, color = year))+
  facet_wrap(~treatment)

ggplot(tbl3_p)+
  geom_density(aes(x = p, color = size))

ggplot(tbl3_psi12)+
  geom_density(aes (x = psi, color = treatment))

ggplot(tbl3_psi23)+
  geom_density(aes (x = psi, color = treatment))

summary(tbl3_phi)
```

















