---
title: "R Notebook"
output: html_notebook
---


```{r}
library(R2jags)
```
# importation des données

```{r}

######  Test avec mes données_construction

t <- BDD_a %>% ungroup () %>% pivot_wider(id_cols = Tag_id, names_from = Year, values_from =Lake)
t[] <- lapply(t, as.character)
t[!is.na(t)] <- "1"
t[is.na(t)] <- "0"
t <- data.frame(sapply(t,as.numeric))
#set.seed(2022)
#t <- t[sample(1:nrow(t), 100),]
t <- as.matrix(t)
```

# création d'un tableau pour tester le model

```{r}
# Define parameter values
n.occasions <- 6                   # Number of capture occasions
marked <- rep(50, n.occasions-1)   # Annual number of newly marked individuals
phi <- 0.65
p <- 0.4

# Define function to simulate a capture-history (CH) matrix
simul.cjs <- function(phi, p, marked){
  CH <- matrix(0, ncol = n.occasions, nrow = sum(marked))
  # Define a vector with the occasion of marking
  mark.occ <- rep(1:length(marked), marked[1:length(marked)])
  # Fill the CH matrix
  for (i in 1:sum(marked)){
    CH[i, mark.occ[i]] <- 1       # Write an 1 at the release occasion
    if (mark.occ[i]==n.occasions) next
    for (t in (mark.occ[i]+1):n.occasions){
      # Bernoulli trial: does individual survive occasion?
      sur <- rbinom(1, 1, phi)
      if (sur==0) break		# If dead, move to next individual 
      # Bernoulli trial: is individual recaptured? 
      rp <- rbinom(1, 1, p)
      if (rp==1) CH[i,t] <- 1
    } #t
  } #i
  return(CH)
}

```

# mise en forme des données pour être fittée

```{r}
CH <-  t #(pour mes données) ou simul.cjs(phi,p, marked)

get.first <- function(x) min(which(x!=0))
f <- apply(CH, 1, get.first)

# Bundle data
nind = nrow(CH)
n.occasions = ncol(CH)
jags.data <- list(y = CH,
                  f = f, 
                  nind = nrow(CH), 
                  n.occasions = ncol(CH))
```

# parametres pour le model CJS_0

```{r}

z.inits <- function(ch){
  state <- ch
  state[state==0] <- 1
  #get.first <- function(x) min(which(x!=0))
  f <- apply(ch, 1, get.first)
  for (i in 1:nrow(ch)){
    state[i,1:f[i]] <- NA
  }
  return(state)
}

# model
cjs_0 <- function()
{
  # Likelihood
  for (i in 1:nind){
    z[i,f[i]] <- 1
    for (t in (f[i]+1):n.occasions){
      z[i,t] ~ dbern(phi * z[i,t-1])
      y[i,t] ~ dbern(p * z[i,t])
      }
    }
  # Priors
  phi ~ dunif(0,1)
  p ~ dunif(0,1)
}

# Initial values

inits <- list(list(phi = 0.5, p = 0.1),#,z = z.inits(CH)),
              list(phi = 0.2, p = 0.9))#,z = z.inits(CH)))
# Parameters monitored
  
parameters <- c("phi", "p")

```

```{r}
# Call JAGS from R (BRT 1 min)
CJS_0 <- jags(data = jags.data,
              inits = inits,
              params = parameters,
              model = cjs_0,
              n.chains = 2,
              #method = 'parallel',
              n.iter = 100,
              n.burnin = 30)

# Summarize posteriors
print(CJS_0, digits = 3)
traceplot(CJS_0, ask =FALSE)
autocorr.plot(CJS_0)


n.iter = 1000
n.chains = 2
n.burnin = 500
samps <- do.call(jags.parallel,list(names(jags.data),inits,parameters,
                               cjs_0,
                               n.iter,n.chains,n.burnin, n.cluster = 2))
```

```{r}
#save(CJS_0, file = "object/CJS_0.RData")
```

#Paramètres pour le model CJS_1

```{r}
z.inits <- function(ch){
  state <- ch
  state[state==0] <- 1
  #get.first <- function(x) min(which(x!=0))
  f <- apply(ch, 1, get.first)
  for (i in 1:nrow(ch)){
    state[i,1:f[i]] <- NA
  }
  return(state)
}
# Initial values

Phi <- matrix(0.5, ncol = n.occasions-1, nrow = nind)
P <- matrix(0.5, ncol = n.occasions-1, nrow = nind)

inits <- list(list(phi = 0.2, Phi = Phi , p = 0.1, P = P, z = z.inits(CH)),
              list(phi = 0.8, Phi = Phi, p = 0.9, P = P, z = z.inits(CH)))
# Parameters monitored
  
parameters <- c("phi", "p")
```


```{r}


cjs_1 <- function()
{
    # Priors
    for (i in 1:nind){
      for (t in 1:(n.occasions-1)){
        Phi[i,t] ~ dnorm(phi,0.1)
        P[i,t] ~ dnorm (p,0.1)
        } #t
      } #i        # Prior for mean survival
    p ~ dunif(0, 1) # Prior for mean recapture
    phi ~ dunif(0, 1)
    
    # Likelihood 
    for (i in 1:nind){
      
      # Define latent state at first capture
      z[i,f[i]] <- 1
      for (t in (f[i]+1):n.occasions){
        # survival process
        
        
        # State process
        z[i,t] ~ dbern(Phi[i,t-1] * z[i,t-1])
        
        # Observation process
        y[i,t] ~ dbern(P[i,t-1] * z[i,t])
        } #t
      } #i
}
```

```{r}
CJS_1 <- jags(data = jags.data, 
                inits = inits, 
                parameters.to.save = parameters, #
                model.file = cjs_1, #
                n.chains = 2, 
                #n.cluster = 2,
                n.iter = 1000, 
                n.burnin = 500)
```

```{r}
print(CJS_1, digits = 3)
traceplot(CJS_1, ask =FALSE)
autocorr.plot(CJS_1)
```

```{r}
#save(CJS_1, file = "object/CJS_1.RData")
```

