---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(FSA)
library(FSAdata)
library(nlstools)
library(tidyverse)
```

```{r}
data <- BDD_a %>% filter(Tag_year == "2016" & Year != "2022") %>% select("Tag_id","Year","Size","Treatment", "Lake")
data <- data %>% mutate(Year = as.numeric(Year)+2015)
data <- data %>% mutate(Treatment = as.numeric(Treatment))
data <- data %>% mutate(Lake = as.numeric(Lake))
data <- na.omit(data)
#data <- data [duplicated(data$Tag_id),]

#df <- data.frame(Tag_id = unique(data$Tag_id), individu = c(1:1549))
#data <- merge(data, df)

#data <- data [,-1]
#data <- data %>% filter(Treatment == "1")
head(data)
table(data$Lake)
```

```{r}
svCom <- vbStarts(Size~Year, data)
svCom
```

```{r}
initKL <- mapply(rep, svCom, c(4,4,1))
fKL <- Size~Linf[Treatment]*(1-exp(-K[Treatment]*(Year-t0)))

#initKLt <- mapply(rep, svCom, c(4,4,1549))
#fKLt <- Size~Linf[Treatment]*(1-exp(-K[Treatment]*(Year-t0[individu])))

initK <- mapply(rep, svCom, c(1,4,1))
fK <- Size~Linf*(1-exp(-K[Treatment]*(Year-t0)))

initL <- mapply(rep, svCom, c(4,1,1))
fL <- Size~Linf[Treatment]*(1-exp(-K*(Year-t0)))

init <- mapply(rep, svCom, c(1,1,1))
f <- Size~Linf*(1-exp(-K*(Year-t0)))

initLake <- mapply(rep, svCom ,c(16,16,1))
fLake <- Size~Linf[Lake]*(1-exp(-K[Lake]*(Year-t0)))
```

```{r}
fitKL <- nls(fKL, data, initKL)
fitK <- nls(fK, data, initK)
fitL <- nls(fL, data, initL)
fit <- nls(f, data, init)
fitLake <- nls(fLake, data, initLake)
#fitKLt <- nls(fKLt, data, initKLt)
```

```{r}
#residPlot(fitGen)
hist(residuals(fitGen), main = "")
```

```{r}
anova(fitK,fitKL)
anova(fitL,fitKL)
anova(fit, fitKL)
anova(fitLake, fitKL)
#anova(fitKLt,fitKL)
```

```{r}
AIC(fitKL,fitL,fitK,fit, fitLake)
```
```{r}
overview(fitKL)
```

```{r}
ggplot()+
  geom_point(aes(x = 1:8, y = 0.8*174*exp(-0.8*(1:8+1.3))), color = "red")+
  geom_point(aes(x = 1:8, y = 0.9*170*exp(-0.9*(1:8+1.3))), color = "blue")+
  geom_point(aes(x = 1:8, y = 1*160*exp(-1*(1:8+1.3))), color = "green")+
  geom_point(aes(x = 1:8, y = 0.9*164*exp(-0.9*(1:8+1.3))))
```

```{r}
data <- BDD_a %>% filter(Tag_year == "2016" & Year != "2022") %>% select("Tag_id","Year","Size","Treatment", "Lake")
data <- data %>% mutate(Year = as.numeric(Year)+2015)
data <- data %>% mutate(Treatment = as.numeric(Treatment))
data <- data %>% filter (Treatment == 4) %>% select ("Tag_id","Year","Size","Lake")

data <- data %>% mutate(Lake = as.numeric(Lake))
data <- data %>% mutate(Lake = factor(Lake))
levels(data$Lake) <- c(1,2,3,4)
data <- data %>% mutate(Lake = as.numeric(Lake))
data <- na.omit(data)
#data <- data [duplicated(data$Tag_id),]

#df <- data.frame(Tag_id = unique(data$Tag_id), individu = c(1:1549))
#data <- merge(data, df)

#data <- data [,-1]
#data <- data %>% filter(Treatment == "1")
head(data)
#summary(data$Lake)
```

```{r}
svCom <- vbStarts(Size~Year, data)
svCom
```

```{r}
init <- mapply(rep, svCom, c(1,1,1))
f <- Size~Linf*(1-exp(-K*(Year-t0)))

initKL <- mapply(rep, svCom, c(4,4,1))
fKL <- Size~Linf[Lake]*(1-exp(-K[Lake]*(Year-t0)))
```

```{r}
fit <- nls(f, data, init)
fitKL <- nls(fKL, data, initKL)
```


```{r}
anova(fit,fitKL)
```

```{r}
AIC(fitKL,fit)
```

